### ISSUE TITLE
Looking to contribute: LA Affordable Housing analysis

### ISSUE THREAD

**Issue by judecalvillo** [Nixonite/HackForLA-Data-Analysis#3]
Hi Allen,

I'm a fan of CFA and Hack for LA. Lookin' to contribute to data science endeavors where/when I can. As such, I had an idea for an analysis of LA's affordable housing data (vis-a-vis other sources), and I'm in the very early stages of executing it. [Check it out >>](https://github.com/judecalvillo/HackForLA-Data-Analysis/tree/master/LA%20Affordable%20Housing%20Projects)

Can I go ahead and 'push' in for a 'pull'? Honestly, though I'm fairly experienced in market research and inf. stats, I'm green to the Git game and would appreciate the practice.

Let me know. Hope all's well.

-Jude C.

**Comment by sjqtentacles** [comment]
sure!

**Comment by judecalvillo** [comment]
Awesome! Thanks, Allen. Like I said, it's super basic right now, but I do hope to flesh this out into something substantive and meaningful as soon as possible.
