### ISSUE TITLE
Quick update on LA Affordable Housing analysis.

### ISSUE THREAD

**Issue by judecalvillo** [Nixonite/HackForLA-Data-Analysis#5]
Quick update, Allen:

It's actually been difficult to come by a per district breakdown of census tracts or ZCTAs, so I can relate the affordable housing data to Census/ACS and other datasets (for multiple years). I put a call into LA City engineering, which resulted in an interesting suggestion (GIS), and I just sent emails to LA Planning and LAECD. One way or another, we'll get that data... and enough to make reliable inferences. 

Hope all's well. 
_Jude_

**Comment by sjqtentacles** [comment]
So I kinda lost interest in this project a long while ago. The people in the mayor/open-data/la office don't seem to give a damn about what they do - I asked for some records, they gave me something unrelated, I asked again, they ignored me. Even when I met in person to speak. 

The open data portal is more or less a dumping of data without regard for it, and it's more of a display than a meaningful/functional tool. 

Either way, hope you learn something from playing around with the data. I just used it to practice some visualization.

**Comment by judecalvillo** [comment]
Saw the visuals. Good stuff, man.

Yeah, I'm beginning to experience the same thing with the city. Hope it's not purposeful. Anyways, I'll be pushing some interesting stuff (IMHO) tomorrow night, ..but if I could get my hands on actual funding dates, that'd be super useful. Without that, I'll either be fundamentally speculating on a major predictor, via function, or I'll be working at a not-so-predictive statistical resolution/"power."

Either way, like you, I'm just lookin' to practice on some cool data sets. Have a good one.

-Jude

---- On Sat, 14 Nov 2015 23:42:07 -0800 Allen S.&lt;notifications@github.com&gt; wrote ---- 

So I kinda lost interest in this project a long while ago. The people in the mayor/open-data/la office don't seem to give a damn about what they do - I asked for some records, they gave me something unrelated, I asked again, they ignored me. Even when I met in person to speak. 
 The open data portal is more or less a dumping of data without regard for it, and it's more of a display than a meaningful/functional tool. 
 Either way, hope you learn something from playing around with the data. I just used it to practice some visualization.
